In [ ]:
# !pip uninstall pandas
# !pip install pandas==1.3.5

# !pip uninstall numpy
# !pip install numpy==1.21.6

# !pip uninstall seaborn
# !pip install seaborn==0.11.2

## 판다스 치트시트 활용
 - 판다스 데이터프레임 생성 연습

In [2]:
import pandas as pd
import numpy as np

In [ ]:
# 판다스, 데이터프레임(DataFrame) 생성
sample_data = {"a":[4,5,6],
               "b":[7,8,9],
               "c":[10,11,12]}

df = pd.DataFrame(sample_data)
df_index = pd.DataFrame(sample_data, index=[1,2,3])

In [ ]:
df

   a  b   c
0  4  7  10
1  5  8  11
2  6  9  12

In [ ]:
df_index

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
df_1 = pd.DataFrame(
    [[4,7,10],
     [5,8,11],
     [6,9,12]],
     index=[1,2,3],
     columns=['a','b','c']
     )

df_1

   a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [ ]:
df_multi_index = pd.DataFrame(
    {"a":[4,5,6],
     "b":[7,8,9],
     "c":[10,11,12]},
     index=pd.MultiIndex.from_tuples(
         [('d', 1), ('d',2), ('e', 2)],
         names=['n','v']
         )
     )

df_multi_index

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [ ]:
pd.DataFrame(
    {"가격":[14000,10550,20000],
     "출시일":["7월", "2월","4월"],
     "색깔":["검정","노랑","검정"]},
     index=pd.MultiIndex.from_tuples(
         [('한국', "A사"), ('한국',"B사"), ('영국', "C사")],
         names=['국가','회사']
         )
     )

          가격 출시일  색깔
국가 회사
한국 A사  14000  7월  검정
   B사  10550  2월  노랑
영국 C사  20000  4월  검정

데이터프레임 Reshaping

In [ ]:
df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two','two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})

In [ ]:
df

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

In [ ]:
df.pivot(index='foo', columns='bar', values='baz')

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [ ]:
df.pivot(index='foo', columns='bar')['baz']

bar  A  B  C
foo
one  1  2  3
two  4  5  6

In [ ]:
df.pivot(index='foo', columns='bar', values=['baz', 'zoo'])

    baz       zoo
bar   A  B  C   A  B  C
foo
one   1  2  3   x  y  z
two   4  5  6   q  w  t

In [ ]:
df = pd.DataFrame({
    "lev1": [1, 1, 1, 2, 2, 2],
    "lev2": [1, 1, 2, 1, 1, 2],
    "lev3": [1, 2, 1, 2, 1, 2],
    "lev4": [1, 2, 3, 4, 5, 6],
    "values": [0, 1, 2, 3, 4, 5]})

df

   lev1  lev2  lev3  lev4  values
0     1     1     1     1       0
1     1     1     2     2       1
2     1     2     1     3       2
3     2     1     2     4       3
4     2     1     1     5       4
5     2     2     2     6       5

In [ ]:
df.pivot(index='lev1', columns=["lev2","lev3"], values='values')

lev2    1         2
lev3    1    2    1    2
lev1
1     0.0  1.0  2.0  NaN
2     4.0  3.0  NaN  5.0

In [ ]:
# melt
df = pd.DataFrame({'A': {0: 'a', 1: 'b', 2: 'c'},
                   'B': {0: 1, 1: 3, 2: 5},
                   'C': {0: 2, 1: 4, 2: 6}})

df

   A  B  C
0  a  1  2
1  b  3  4
2  c  5  6

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B'])

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B', 'C'])

   A variable  value
0  a        B      1
1  b        B      3
2  c        B      5
3  a        C      2
4  b        C      4
5  c        C      6

In [ ]:
pd.melt(df, id_vars=['A'], value_vars=['B'],
        var_name='열', value_name='B_값')

   A  열  B_값
0  a  B    1
1  b  B    3
2  c  B    5

In [ ]:
pd.melt(df)

  variable value
0        A     a
1        A     b
2        A     c
3        B     1
4        B     3
5        B     5
6        C     2
7        C     4
8        C     6

concat()

In [ ]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                   columns=['letter', 'number'])

df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])

In [ ]:
display(df1)
display(df2)

  letter  number
0      a       1
1      b       2

  letter  number
0      c       3
1      d       4

In [ ]:
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [ ]:
df3 = pd.DataFrame([['e', 5, 'cat'], ['f', 6, 'dog']],
                   columns=['letter', 'number', 'animal'])

In [ ]:
df3

  letter  number animal
0      e       5    cat
1      f       6    dog

In [ ]:
pd.concat([df1, df3], sort=False) # False가 디폴트값

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      e       5    cat
1      f       6    dog

In [ ]:
pd.concat([df1, df3], sort=True)

  animal letter  number
0    NaN      a       1
1    NaN      b       2
0    cat      e       5
1    dog      f       6

In [ ]:
pd.concat([df1, df3], join="inner") #서로 겹치는 열만 default 는 outer

  letter  number
0      a       1
1      b       2
0      e       5
1      f       6

In [ ]:
df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
                   columns=['animal', 'name'])

df4

   animal    name
0    bird   polly
1  monkey  george

In [ ]:
pd.concat([df1, df4], axis=1)

  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

자주 사용하는 기능 익히기
1. sort_values()
2. rename()
3. sort_index()
4. reset_indeX()
5. drop()

In [3]:
import numpy as np

df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']})
df

  col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F

In [ ]:
df.sort_values(by='col1', ascending=False)

  col1  col2  col3 col4
4    D     7     2    e
5    C     4     3    F
2    B     9     9    c
0    A     2     0    a
1    A     1     1    B
3  NaN     8     4    D

In [ ]:
df.sort_values(by=['col1'])

  col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D

In [ ]:
 df.sort_values(by=['col1', 'col2'])

  col1  col2  col3 col4
1    A     1     1    B
0    A     2     0    a
2    B     9     9    c
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D

In [ ]:
df.sort_values(by='col1', ascending=False, na_position='first')

  col1  col2  col3 col4
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F
2    B     9     9    c
0    A     2     0    a
1    A     1     1    B

rename() 함수 익히기

In [ ]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df

   A  B
0  1  4
1  2  5
2  3  6

In [ ]:
df.rename(columns={"A": "a", "B": "b"})

   a  b
0  1  4
1  2  5
2  3  6

In [ ]:
df.rename(index={0: "x", 1: "y", 2: "z"})

   A  B
x  1  4
y  2  5
z  3  6

In [ ]:
df.rename(str.lower, axis='columns')

   a  b
0  1  4
1  2  5
2  3  6

In [ ]:
df.rename({1: 10, 2: 20}, axis='index')

    A  B
0   1  4
10  2  5
20  3  6

sort_index() 익히기

In [ ]:
df = pd.DataFrame([1, 2, 3, 4, 5], index=[100, 29, 234, 1, 150],
                  columns=['A'])

df

     A
100  1
29   2
234  3
1    4
150  5

In [ ]:
df.sort_index()

     A
1    4
29   2
100  1
150  5
234  3

In [ ]:
df.sort_index(ascending=False)

     A
234  3
150  5
100  1
29   2
1    4

reset_index() 익히기

In [ ]:
df = pd.DataFrame([('bird', 389.0),
                   ('bird', 24.0),
                   ('mammal', 80.5),
                   ('mammal', np.nan)],
                  index=['falcon', 'parrot', 'lion', 'monkey'],
                  columns=('class', 'max_speed'))

df

         class  max_speed
falcon    bird      389.0
parrot    bird       24.0
lion    mammal       80.5
monkey  mammal        NaN

In [ ]:
df.reset_index()

    index   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [ ]:
df.reset_index(drop=True) # 인덱스 삭제하고 새롭게 0,1,2,3

    class  max_speed
0    bird      389.0
1    bird       24.0
2  mammal       80.5
3  mammal        NaN

drop()

In [ ]:
df = pd.DataFrame(np.arange(12).reshape(3, 4),
                  columns=['A', 'B', 'C', 'D'])

df

   A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
df.drop(['B', 'C'], axis=1)

   A   D
0  0   3
1  4   7
2  8  11

In [ ]:
df.drop(columns=['B', 'C'])

   A   D
0  0   3
1  4   7
2  8  11

In [ ]:
df.drop([0, 1])

   A  B   C   D
2  8  9  10  11

In [ ]:
midx = pd.MultiIndex(levels=[['lama', 'cow', 'falcon'],
                             ['speed', 'weight', 'length']],
                     codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
                            [0, 1, 2, 0, 1, 2, 0, 1, 2]])

df = pd.DataFrame(index=midx, columns=['big', 'small'],
                  data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
                        [250, 150], [1.5, 0.8], [320, 250],
                        [1, 0.8], [0.3, 0.2]])

df

                 big  small
lama   speed    45.0   30.0
       weight  200.0  100.0
       length    1.5    1.0
cow    speed    30.0   20.0
       weight  250.0  150.0
       length    1.5    0.8
falcon speed   320.0  250.0
       weight    1.0    0.8
       length    0.3    0.2

In [ ]:
df.drop(index='cow', columns='small')

                 big
lama   speed    45.0
       weight  200.0
       length    1.5
falcon speed   320.0
       weight    1.0
       length    0.3

In [ ]:
df.drop(index='length', level=1)

                 big  small
lama   speed    45.0   30.0
       weight  200.0  100.0
cow    speed    30.0   20.0
       weight  250.0  150.0
falcon speed   320.0  250.0
       weight    1.0    0.8

In [ ]:
df.drop(index='lama', level=0)

                 big  small
cow    speed    30.0   20.0
       weight  250.0  150.0
       length    1.5    0.8
falcon speed   320.0  250.0
       weight    1.0    0.8
       length    0.3    0.2

데이터 추출 (행 기준)

In [ ]:
df = pd.DataFrame({"ID":[1,2,3,3],
                   "국어":[80,90,75,75],
                   "영어":[85,100,70,70],
                   "수학":[75,95,65,75]})

In [ ]:
df

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95
2   3  75   70  65
3   3  75   70  75

In [ ]:
df[df.국어>80] #df[df['국어']>80]

   ID  국어   영어  수학
1   2  90  100  95

In [ ]:
df.drop_duplicates()

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95
2   3  75   70  65
3   3  75   70  75

In [ ]:
df.drop_duplicates(subset='ID')

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95
2   3  75   70  65

In [ ]:
df.head(2)

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95

In [ ]:
df.tail(2)

   ID  국어  영어  수학
2   3  75  70  65
3   3  75  70  75

In [ ]:
df.sample(2)

   ID  국어  영어  수학
2   3  75  70  65
0   1  80  85  75

In [ ]:
df.sample(frac=0.5)

   ID  국어   영어  수학
1   2  90  100  95
3   3  75   70  75

In [ ]:
df.nlargest(1, '영어')

   ID  국어   영어  수학
1   2  90  100  95

In [ ]:
df.nlargest(3, '영어')

   ID  국어   영어  수학
1   2  90  100  95
0   1  80   85  75
2   3  75   70  65

In [ ]:
df.nsmallest(3, '수학')

   ID  국어  영어  수학
2   3  75  70  65
0   1  80  85  75
3   3  75  70  75

In [ ]:
df.iloc[0, 2]

85

In [ ]:
df.iloc[1:3]

   ID  국어   영어  수학
1   2  90  100  95
2   3  75   70  65

In [ ]:
df.iloc[:,:]

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95
2   3  75   70  65
3   3  75   70  75

In [ ]:
df.iloc[1:4,:]

   ID  국어   영어  수학
1   2  90  100  95
2   3  75   70  65
3   3  75   70  75

In [ ]:
df.iloc[1:4,:3]

   ID  국어   영어
1   2  90  100
2   3  75   70
3   3  75   70

표 1.2.11.3 loc[ ]를 활용한 데이터-열 추출

In [ ]:
df.loc[:,['국어','영어']]

   국어   영어
0  80   85
1  90  100
2  75   70
3  75   70

In [ ]:
df.loc[:2,['국어','영어']]

   국어   영어
0  80   85
1  90  100
2  75   70

In [ ]:
df.loc[df['국어']>=80, ['국어','수학']]

   국어  수학
0  80  75
1  90  95

표 1.2.11.5 비교 연산자를 활용한 데이터 선택

In [ ]:
df[df['국어']==75]

   ID  국어  영어  수학
2   3  75  70  65
3   3  75  70  75

In [ ]:
df[df['국어']!=75]

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95

In [ ]:
df[df['국어']>=80]

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95

In [ ]:
df

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95
2   3  75   70  65
3   3  75   70  75

In [ ]:
df[(df['영어']>=80) & (df['국어']>=80)]

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95

In [ ]:
df[(df['수학']>=70) | (df['국어']>=80)]

   ID  국어   영어  수학
0   1  80   85  75
1   2  90  100  95
3   3  75   70  75

In [ ]:
df[~(df['수학']>=70)]

   ID  국어  영어  수학
2   3  75  70  65

데이터 요약(Summarize Data)

In [ ]:
df = pd.DataFrame({"ID":[1,2,3,4,5],
                   "국어":[80,90,75,100,80],
                   "영어":[85,100,70,70, 75],
                   "수학":[75,95,65,95,np.nan]})

In [ ]:
df

   ID   국어   영어    수학
0   1   80   85  75.0
1   2   90  100  95.0
2   3   75   70  65.0
3   4  100   70  95.0
4   5   80   75   NaN

In [ ]:
df['영어'].value_counts()

70     2
85     1
100    1
75     1
Name: 영어, dtype: int64

In [ ]:
df.shape

(5, 4)

In [ ]:
df['영어'].nunique()

4

In [ ]:
df['영어'].unique()

array([ 85, 100,  70,  75])

In [ ]:
df.describe()

             ID     국어          영어    수학
count  5.000000    5.0    5.000000   4.0
mean   3.000000   85.0   80.000000  82.5
std    1.581139   10.0   12.747549  15.0
min    1.000000   75.0   70.000000  65.0
25%    2.000000   80.0   70.000000  72.5
50%    3.000000   80.0   75.000000  85.0
75%    4.000000   90.0   85.000000  95.0
max    5.000000  100.0  100.000000  95.0

In [ ]:
df.sum()

ID     15.0
국어    425.0
영어    400.0
수학    330.0
dtype: float64

In [ ]:
df[['국어','영어','수학']].sum()

국어    425.0
영어    400.0
수학    330.0
dtype: float64

In [ ]:
df[['국어','영어','수학']].median()

국어    80.0
영어    75.0
수학    85.0
dtype: float64

In [ ]:
df['수학'].quantile([0.25, 0.5, 0.75])

0.25    72.5
0.50    85.0
0.75    95.0
Name: 수학, dtype: float64

In [ ]:
df['수학'].var() #분산

225.0

In [ ]:
df['수학'].std()

15.0

In [ ]:
df['수학'].min()

65.0

In [ ]:
df['수학'].max()

95.0

In [ ]:
df['수학'].mean()

82.5

In [ ]:
df[['국어','영어','수학']].count()

국어    5
영어    5
수학    4
dtype: int64

결측치 처리(Handling Missing Data)

In [ ]:
df

   ID   국어   영어    수학
0   1   80   85  75.0
1   2   90  100  95.0
2   3   75   70  65.0
3   4  100   70  95.0
4   5   80   75   NaN

In [ ]:
df.dropna()

   ID   국어   영어    수학
0   1   80   85  75.0
1   2   90  100  95.0
2   3   75   70  65.0
3   4  100   70  95.0

In [ ]:
df.dropna(axis=1)

   ID   국어   영어
0   1   80   85
1   2   90  100
2   3   75   70
3   4  100   70
4   5   80   75

In [ ]:
df.fillna(9999)

   ID   국어   영어      수학
0   1   80   85    75.0
1   2   90  100    95.0
2   3   75   70    65.0
3   4  100   70    95.0
4   5   80   75  9999.0

In [ ]:
df.fillna(df['수학'].mean())

   ID   국어   영어    수학
0   1   80   85  75.0
1   2   90  100  95.0
2   3   75   70  65.0
3   4  100   70  95.0
4   5   80   75  82.5

열 생성

In [ ]:
df = pd.DataFrame({"A":range(1, 13), 
              "B":np.random.randint(0, 12, size=12)})

In [ ]:
df

     A   B
0    1   8
1    2   0
2    3   6
3    4  11
4    5   4
5    6   9
6    7   3
7    8   3
8    9  11
9   10   3
10  11   7
11  12   6

In [ ]:
df.assign(plus = lambda x:df['A']+df['B'])

     A   B  plus
0    1   8     9
1    2   0     2
2    3   6     9
3    4  11    15
4    5   4     9
5    6   9    15
6    7   3    10
7    8   3    11
8    9  11    20
9   10   3    13
10  11   7    18
11  12   6    18

In [ ]:
df['plus'] = df['A']+df['B']
df

     A   B  plus
0    1   8     9
1    2   0     2
2    3   6     9
3    4  11    15
4    5   4     9
5    6   9    15
6    7   3    10
7    8   3    11
8    9  11    20
9   10   3    13
10  11   7    18
11  12   6    18

In [ ]:
#qcut : 구간을 나눈다

pd.qcut(df['plus'], 3 , labels={"A", "B", 'C'})

0     A
1     A
2     A
3     B
4     A
5     B
6     B
7     B
8     C
9     B
10    C
11    C
Name: plus, dtype: category
Categories (3, object): ['A' < 'B' < 'C']

In [ ]:
df.max(axis=1)

0      9
1      2
2      9
3     15
4      9
5     15
6     10
7     11
8     20
9     13
10    18
11    18
dtype: int64

In [ ]:
df.max(axis=0)

A       12
B       11
plus    20
dtype: int64

In [ ]:
df

     A   B  plus
0    1   8     9
1    2   0     2
2    3   6     9
3    4  11    15
4    5   4     9
5    6   9    15
6    7   3    10
7    8   3    11
8    9  11    20
9   10   3    13
10  11   7    18
11  12   6    18

In [ ]:
df['B'].clip(lower=3, upper=8) # 3이하는 3, 8이상은 8로 바꿔준다.

0     8
1     3
2     6
3     8
4     4
5     8
6     3
7     3
8     8
9     3
10    7
11    6
Name: B, dtype: int64

In [ ]:
df = df.assign(minus = lambda x:df['B']-df['A'])

In [ ]:
df

     A   B  plus  minus
0    1   8     9      7
1    2   0     2     -2
2    3   6     9      3
3    4  11    15      7
4    5   4     9     -1
5    6   9    15      3
6    7   3    10     -4
7    8   3    11     -5
8    9  11    20      2
9   10   3    13     -7
10  11   7    18     -4
11  12   6    18     -6

In [ ]:
df.abs()

     A   B  plus  minus
0    1   8     9      7
1    2   0     2      2
2    3   6     9      3
3    4  11    15      7
4    5   4     9      1
5    6   9    15      3
6    7   3    10      4
7    8   3    11      5
8    9  11    20      2
9   10   3    13      7
10  11   7    18      4
11  12   6    18      6

In [ ]:
df['minus'].abs()

0     7
1     2
2     3
3     7
4     1
5     3
6     4
7     5
8     2
9     7
10    4
11    6
Name: minus, dtype: int64

데이터 그룹화(Group Data)

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("mpg")
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite

In [ ]:
df.groupby(by="origin").size() #value_counts()

origin
europe     70
japan      79
usa       249
dtype: int64

In [ ]:
df.groupby(by="origin").min()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,name
origin,,,,,,,,
europe,16.2,4,68.0,46.0,1825,12.2,70,audi 100 ls
japan,18.0,3,70.0,52.0,1613,11.4,70,datsun 1200
usa,9.0,4,85.0,52.0,1800,8.0,70,amc ambassador brougham

In [ ]:
df.groupby(by="origin").mean()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year
origin,,,,,,,
europe,27.891429,4.157143,109.142857,80.558824,2423.300000,16.787143,75.814286
japan,30.450633,4.101266,102.708861,79.835443,2221.227848,16.172152,77.443038
usa,20.083534,6.248996,245.901606,119.048980,3361.931727,15.033735,75.610442

In [ ]:
df.groupby(by="origin")[['horsepower', 'weight']].mean()

        horsepower       weight
origin
europe   80.558824  2423.300000
japan    79.835443  2221.227848
usa     119.048980  3361.931727

In [ ]:
df.groupby(['model_year',"origin"])['weight'].mean()

model_year  origin
70          europe    2309.200000
            japan     2251.000000
            usa       3716.500000
71          europe    2024.000000
            japan     1936.000000
            usa       3401.600000
72          europe    2573.200000
            japan     2300.400000
            usa       3682.666667
73          europe    2335.714286
            japan     2397.250000
            usa       3821.448276
74          europe    2139.333333
            japan     2053.000000
            usa       3503.333333
75          europe    2571.166667
            japan     2303.250000
            usa       3533.200000
76          europe    2611.000000
            japan     2217.500000
            usa       3405.409091
77          europe    2138.750000
            japan     2295.833333
            usa       3422.000000
78          europe    2691.666667
            japan     2221.250000
            usa       3141.136364
79          europe    2693.750000
            japan     1997.500000
            usa       3210.217391
80          europe    2348.000000
            japan     2290.307692
            usa       2822.428571
81          europe    2725.000000
            japan     2269.166667
            usa       2695.000000
82          europe    2055.000000
            japan     2132.777778
            usa       2637.750000
Name: weight, dtype: float64

In [ ]:
df = sns.load_dataset("mpg")
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite

In [ ]:
df.tail(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
395,32.0,4,135.0,84.0,2295,11.6,82,usa,dodge rampage
396,28.0,4,120.0,79.0,2625,18.6,82,usa,ford ranger
397,31.0,4,119.0,82.0,2720,19.4,82,usa,chevy s-10

In [ ]:
df['cylinders'].unique()

array([8, 4, 6, 3, 5])

In [ ]:
df['cylinders'].rank(method='min')

0      296.0
1      296.0
2      296.0
3      296.0
4      296.0
       ...
393      5.0
394      5.0
395      5.0
396      5.0
397      5.0
Name: cylinders, Length: 398, dtype: float64

In [ ]:
df['cylinders'].rank(method='dense')

0      5.0
1      5.0
2      5.0
3      5.0
4      5.0
      ...
393    2.0
394    2.0
395    2.0
396    2.0
397    2.0
Name: cylinders, Length: 398, dtype: float64

In [ ]:
df['cylinders'].rank(method='max')

0      398.0
1      398.0
2      398.0
3      398.0
4      398.0
       ...
393    208.0
394    208.0
395    208.0
396    208.0
397    208.0
Name: cylinders, Length: 398, dtype: float64

In [ ]:
df['cylinders'].rank(method='average')

0      347.0
1      347.0
2      347.0
3      347.0
4      347.0
       ...
393    106.5
394    106.5
395    106.5
396    106.5
397    106.5
Name: cylinders, Length: 398, dtype: float64

In [ ]:
df['cylinders'].rank(ascending=False, method='dense')

0      1.0
1      1.0
2      1.0
3      1.0
4      1.0
      ...
393    4.0
394    4.0
395    4.0
396    4.0
397    4.0
Name: cylinders, Length: 398, dtype: float64

In [ ]:
df = pd.DataFrame({"ID":[1,2,3,4,5],
                   "국어":[80,90,75,100,80],
                   "영어":[85,100,70,70, 75],
                   "수학":[75,95,65,95,np.nan]})

In [ ]:
df

   ID   국어   영어    수학
0   1   80   85  75.0
1   2   90  100  95.0
2   3   75   70  65.0
3   4  100   70  95.0
4   5   80   75   NaN

In [ ]:
df['국어'].cumsum()

0     80
1    170
2    245
3    345
4    425
Name: 국어, dtype: int64

In [ ]:
df['국어'].cummax()

0     80
1     90
2     90
3    100
4    100
Name: 국어, dtype: int64

In [ ]:
df['국어'].cummin()

0    80
1    80
2    75
3    75
4    75
Name: 국어, dtype: int64

In [ ]:
df['국어'].cumprod() #누적곱

0            80
1          7200
2        540000
3      54000000
4    4320000000
Name: 국어, dtype: int64

데이터 병합(Combine Data Sets)

In [ ]:
df.groupby(['model_year',"origin"])['weight'].mean().to_frame()

                        weight
model_year origin
70         europe  2309.200000
           japan   2251.000000
           usa     3716.500000
71         europe  2024.000000
           japan   1936.000000
           usa     3401.600000
72         europe  2573.200000
           japan   2300.400000
           usa     3682.666667
73         europe  2335.714286
           japan   2397.250000
           usa     3821.448276
74         europe  2139.333333
           japan   2053.000000
           usa     3503.333333
75         europe  2571.166667
           japan   2303.250000
           usa     3533.200000
76         europe  2611.000000
           japan   2217.500000
           usa     3405.409091
77         europe  2138.750000
           japan   2295.833333
           usa     3422.000000
78         europe  2691.666667
           japan   2221.250000
           usa     3141.136364
79         europe  2693.750000
           japan   1997.500000
           usa     3210.217391
80         europe  2348.000000
           japan   2290.307692
           usa     2822.428571
81         europe  2725.000000
           japan   2269.166667
           usa     2695.000000
82         europe  2055.000000
           japan   2132.777778
           usa     2637.750000

In [ ]:
df = pd.DataFrame({"A":range(1, 6), 
              "B":np.random.randint(0, 10, size=5)})

In [ ]:
df

   A  B
0  1  1
1  2  1
2  3  5
3  4  5
4  5  8

In [ ]:
df.shift(1)

     A    B
0  NaN  NaN
1  1.0  1.0
2  2.0  1.0
3  3.0  5.0
4  4.0  5.0

In [ ]:
df.shift(-1)

     A    B
0  2.0  1.0
1  3.0  5.0
2  4.0  5.0
3  5.0  8.0
4  NaN  NaN

In [ ]:
df['cylinders'].value_counts()

4    204
8    103
6     84
3      4
5      3
Name: cylinders, dtype: int64

In [ ]:
df['cylinders'].rank(pct=True) # pct 는 퍼센트 의미

0      0.871859
1      0.871859
2      0.871859
3      0.871859
4      0.871859
         ...
393    0.267588
394    0.267588
395    0.267588
396    0.267588
397    0.267588
Name: cylinders, Length: 398, dtype: float64

In [ ]:
df['cylinders'].cumsum()

0         8
1        16
2        24
3        32
4        40
       ...
393    2155
394    2159
395    2163
396    2167
397    2171
Name: cylinders, Length: 398, dtype: int64

데이터 병합(Combine Data Sets)

In [ ]:
adf = pd.DataFrame({"x1": ["A", "B", "C"], "x2": [1, 2, 3]})
adf

  x1  x2
0  A   1
1  B   2
2  C   3

In [ ]:
bdf = pd.DataFrame({"x1": ["A", "B", "D"], "x3": ["T", "F", "T"]})
bdf

  x1 x3
0  A  T
1  B  F
2  D  T

In [ ]:
pd.merge(adf, bdf, on='x1')

  x1  x2 x3
0  A   1  T
1  B   2  F

In [ ]:
pd.merge(adf, bdf, how='right', on='x1')

  x1   x2 x3
0  A  1.0  T
1  B  2.0  F
2  D  NaN  T

In [ ]:
pd.merge(adf, bdf, how='left', on='x1')

  x1  x2   x3
0  A   1    T
1  B   2    F
2  C   3  NaN

In [ ]:
pd.merge(adf, bdf, how='outer', on='x1')

  x1   x2   x3
0  A  1.0    T
1  B  2.0    F
2  C  3.0  NaN
3  D  NaN    T

In [ ]:
pd.merge(adf, bdf, how='inner', on='x1') # inner 가 기본값

  x1  x2 x3
0  A   1  T
1  B   2  F

In [ ]:
adf.x1.isin(bdf.x1)

0     True
1     True
2    False
Name: x1, dtype: bool

In [ ]:
adf[adf.x1.isin(bdf.x1)]

  x1  x2
0  A   1
1  B   2

In [ ]:
adf[~adf.x1.isin(bdf.x1)]

  x1  x2
2  C   3